# Generated by Django 2.0.7 on 2018-08-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
